---
text: "Interests and Future Pursuits"
---

My long-term goal is to start an agroforestry consulting business and provide
environmental services to farmers and the general public. I also hope to be
able to conduct further research in my field of study, such as by developing new
agricultural tactics to benefit air and water quality. Additionally, I hope to
continue developing new methods of using microwave remote sensing in agricultural 
regions such as those found in the US Corn Belt.

As manipulating and analyzing data is an important component of my work now and
will continue to be so going forth, I will likely continue using R and RStudio 
for much of my career. Many of the packages that I have become familiar with in
this class will come in handy. For instance, as I mentioned before, the 
tabulizer package will continue to be useful for reading tables from .pdf files
and converting them to more useful data types. Additionally, the lubridate
package will be very helpful for working with categorical data involving dates 
and times, as it has been in this class This will be very useful for tracking
datasets over time, such as those involving crop progress reports. Finally, I have
enjoyed learning about other tidyverse packages, such as dplyr, which has been
very useful for analyzing complex and messy datasets in a variety of subject 
areas.
